### ISSUE TITLE
Principles

### ISSUE THREAD

**Issue by danimesq** [ZeroCoinOrganization/Zerocoin-wallet#21]
- [ ] Being programmed in visual event sheets that even newbie users can audit and contribute (https://github.com/eventlr-engine/Eventlr/issues/23)
- [ ] Great TPS like EOS (https://github.com/ZeroCoinOrganization/Zerocoin-wallet/issues/1)
- [ ] Having all current Bitcoin balances in a block (acting like a fork but not being one, making Bitcoin users to want to hold Zerocoin - https://github.com/ZeroCoinOrganization/Zerocoin-wallet/issues/18)
